/* eslint-disable */
/**
 * Generated API references.
 *
 * NOTE: In a full Convex setup, this file is generated by `npx convex dev`.
 * This repo keeps a lightweight runtime export so Next.js can build without
 * pulling Convex function source files into the TypeScript program.
 */

import { anyApi, componentsGeneric } from "convex/server";

// Public + internal function references (runtime proxy objects).
export const api = anyApi as any;
export const internal = anyApi as any;

// Convex components (e.g. @convex-dev/better-auth)
export const components = componentsGeneric() as any;

