/* eslint-disable */
/**
 * Generated data model types.
 *
 * NOTE: In a full Convex setup, this file is generated by `npx convex dev`.
 * For the Next.js app build, we only need a placeholder type.
 */

export type DataModel = any;

