/* eslint-disable */
/**
 * Generated CRPC metadata for better-convex.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by scripts/generate-convex-meta.ts.
 *
 * To regenerate:
 *   node --experimental-strip-types scripts/generate-convex-meta.ts
 */

export const meta = {
  "functions/agents": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "getBySlug": {
      "type": "query",
      "auth": "optional"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/agentSkills": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/agentThreads": {
    "addAgentMessage": {
      "type": "mutation"
    },
    "addMessage": {
      "type": "mutation",
      "auth": "required"
    },
    "closeThread": {
      "type": "mutation",
      "auth": "required"
    },
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/aiUsage": {
    "list": {
      "type": "query",
      "auth": "required"
    },
    "logUsage": {
      "type": "mutation"
    },
    "stats": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/alerts": {
    "acknowledge": {
      "type": "mutation",
      "auth": "required"
    },
    "createInternal": {
      "type": "mutation"
    },
    "list": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/ap2": {
    "capture": {
      "type": "mutation",
      "auth": "required"
    },
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "settle": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/apiTokens": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "revoke": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/approvalWorkflows": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "resolveGate": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/auditLogs": {
    "list": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/automationRules": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/botGroups": {
    "addMember": {
      "type": "mutation",
      "auth": "required"
    },
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "removeMember": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/botGuidelines": {
    "list": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/botLogs": {
    "list": {
      "type": "query",
      "auth": "required"
    },
    "push": {
      "type": "mutation",
      "auth": "optional"
    },
    "stream": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/botMemory": {
    "botStore": {
      "type": "mutation",
      "auth": "optional"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "upsert": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/botReleaseNotes": {
    "list": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/bots": {
    "get": {
      "type": "query",
      "auth": "required"
    },
    "heartbeat": {
      "type": "mutation",
      "auth": "optional"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "updateStatus": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/botSecrets": {
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "set": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/botSkills": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/botTasks": {
    "assign": {
      "type": "mutation",
      "auth": "required"
    },
    "cancel": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "listByBot": {
      "type": "query",
      "auth": "required"
    },
    "listByTask": {
      "type": "query",
      "auth": "required"
    },
    "updateStatus": {
      "type": "mutation",
      "auth": "optional"
    }
  },
  "functions/channels": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "deliveries": {
      "type": "query",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "recordDelivery": {
      "type": "mutation"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/checkout": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "transition": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/comments": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/connectors": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "sync": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/costBudgets": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/dashboard": {
    "activityFeed": {
      "type": "query",
      "auth": "required"
    },
    "recommendedActions": {
      "type": "query",
      "auth": "required"
    },
    "stats": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/disputes": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "resolve": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/escalations": {
    "createRule": {
      "type": "mutation",
      "auth": "required"
    },
    "evaluate": {
      "type": "mutation"
    },
    "listRules": {
      "type": "query",
      "auth": "required"
    },
    "removeRule": {
      "type": "mutation",
      "auth": "required"
    },
    "updateRule": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/milestones": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/missionStatements": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "listByProject": {
      "type": "query",
      "auth": "required"
    },
    "listRecent": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/notifications": {
    "list": {
      "type": "query",
      "auth": "required"
    },
    "markAllRead": {
      "type": "mutation",
      "auth": "required"
    },
    "markRead": {
      "type": "mutation",
      "auth": "required"
    },
    "unreadCount": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/orders": {
    "createFromCheckout": {
      "type": "mutation"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "updateStatus": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/paymentProviders": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/pipelineTemplates": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "incrementUsage": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/products": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/projectMembers": {
    "add": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "updateRole": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/projects": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/savedViews": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/scheduler": {
    "list": {
      "type": "query",
      "auth": "required"
    },
    "processScheduled": {
      "type": "mutation"
    },
    "scheduleTask": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/serviceAgreements": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "terminate": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/sprints": {
    "addTask": {
      "type": "mutation",
      "auth": "required"
    },
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "removeTask": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/subtasks": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "toggle": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/systemHealth": {
    "get": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/taskAttachments": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/taskDependencies": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/tasks": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/taskSuggestions": {
    "accept": {
      "type": "mutation",
      "auth": "required"
    },
    "createInternal": {
      "type": "mutation"
    },
    "dismiss": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    }
  },
  "functions/taskTemplates": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/teams": {
    "addMember": {
      "type": "mutation",
      "auth": "required"
    },
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "removeMember": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/timeEntries": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "listByTask": {
      "type": "query",
      "auth": "required"
    },
    "listByUser": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/users": {
    "list": {
      "type": "query",
      "auth": "required"
    },
    "me": {
      "type": "query",
      "auth": "required"
    },
    "updateMe": {
      "type": "mutation",
      "auth": "required"
    },
    "updateRole": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/webhooks": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "deliveries": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/webhookSubscriptions": {
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "remove": {
      "type": "mutation",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/workflows": {
    "completeStep": {
      "type": "mutation"
    },
    "create": {
      "type": "mutation",
      "auth": "required"
    },
    "get": {
      "type": "query",
      "auth": "required"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "startRun": {
      "type": "mutation"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/workspaces": {
    "get": {
      "type": "query",
      "auth": "required"
    },
    "update": {
      "type": "mutation",
      "auth": "required"
    }
  },
  "functions/x402": {
    "authorize": {
      "type": "mutation"
    },
    "list": {
      "type": "query",
      "auth": "required"
    },
    "transition": {
      "type": "mutation",
      "auth": "required"
    }
  }
} as const;
