/* eslint-disable */
/**
 * Generated helper types for better-convex.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by scripts/generate-convex-meta.ts.
 */

import type { api } from "./api";
import type { meta } from "./meta";

export type Api = typeof api;
export type Meta = typeof meta;
