import { NextResponse } from "next/server";

export const runtime = "nodejs";

/**
 * Serves Swagger UI for the OpenAPI spec (#41).
 *
 * GET /api/docs → HTML page with embedded Swagger UI
 * pointing at /openapi.json (generated by `pnpm openapi`).
 */
export function GET() {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Whale API Docs</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />
  <style>
    body { margin: 0; background: #1a1a2e; }
    .swagger-ui .topbar { display: none; }
    .swagger-ui { max-width: 1200px; margin: 0 auto; padding: 2rem 1rem; }
    /* dark mode tweaks */
    .swagger-ui .info .title { color: #e0e0e0; }
    .swagger-ui .info .description p { color: #b0b0b0; }
    .swagger-ui .opblock-tag { color: #e0e0e0; }
    .swagger-ui .opblock .opblock-summary-method { font-weight: 700; }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    SwaggerUIBundle({
      url: '/openapi.json',
      dom_id: '#swagger-ui',
      deepLinking: true,
      presets: [SwaggerUIBundle.presets.apis],
      layout: 'BaseLayout',
    });
  </script>
</body>
</html>`;

  return new NextResponse(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
